// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minibank.Data;
using Minibank.Data.DatabaseLayer.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Minibank.Data.Migrations
{
    [DbContext(typeof(MinibankContext))]
    [Migration("20220330204052_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Minibank.Data.Accounts.BankAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("balance");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateClose")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_close");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_open");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_open");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("bank_account");
                });

            modelBuilder.Entity("Minibank.Data.Transfers.MoneyTransferEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("FromBankAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_bank_account_id");

                    b.Property<string>("ToBankAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_bank_account_id");

                    b.HasKey("Id");

                    b.HasIndex("FromBankAccountId");

                    b.HasIndex("ToBankAccountId");

                    b.ToTable("money_transfer");
                });

            modelBuilder.Entity("Minibank.Data.Users.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Minibank.Data.Accounts.BankAccountEntity", b =>
                {
                    b.HasOne("Minibank.Data.Users.UserEntity", "OwnerUser")
                        .WithMany("BankAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Minibank.Data.Transfers.MoneyTransferEntity", b =>
                {
                    b.HasOne("Minibank.Data.Accounts.BankAccountEntity", "FromBankAccount")
                        .WithMany("MoneyTransfersFromAccount")
                        .HasForeignKey("FromBankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Minibank.Data.Accounts.BankAccountEntity", "ToBankAccount")
                        .WithMany("MoneyTransfersToAccount")
                        .HasForeignKey("ToBankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBankAccount");

                    b.Navigation("ToBankAccount");
                });

            modelBuilder.Entity("Minibank.Data.Accounts.BankAccountEntity", b =>
                {
                    b.Navigation("MoneyTransfersFromAccount");

                    b.Navigation("MoneyTransfersToAccount");
                });

            modelBuilder.Entity("Minibank.Data.Users.UserEntity", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
